[package]
name = "skript-lsp"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["core-library", "parser-wasm", "skript-parser", "skripthub", "ssg", "syntax-pattern-parser", "syntaxes", "test-components/catalog-data-addon", "test-components/dynamic-syntax-addon", "test-components/effect-addon", "test-components/matching-addon", "test-components/text-macro-addon", "test-components/tree-macro-addon", "utilities/*", "xtask"]

[dependencies]
parser-wasm = { path = "parser-wasm" }
syntax-pattern-parser = { path = "syntax-pattern-parser" }

[dev-dependencies]
wit-component = "=0.253.0"

[profile.core-library]
inherits = "release"
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "debuginfo"
