[package]
name = "effect-command-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "effectcommandcli"
path = "src/main.rs"

[dependencies]
miette = { version = "=7.6.0", default-features = false, features = ["fancy-no-backtrace"] }
parser-wasm = { path = "../../parser-wasm" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["raw_value"] }
skript-lsp = { path = "../.." }
skript-parser = { path = "../../skript-parser" }
ssg = { path = "../../ssg" }
syntax-pattern-parser = { path = "../../syntax-pattern-parser" }
syntaxes = { path = "../../syntaxes" }
thiserror = "2.0.17"
