[package]
name = "parser-wasm"
version = "0.1.0"
edition = "2024"

[features]
default = ["host"]
host = ["dep:wasmtime"]

[dependencies]
thiserror = "2.0.17"
wasmtime = { version = "=43.0.0", default-features = false, features = ["component-model", "cranelift", "runtime", "std"], optional = true }

[dev-dependencies]
wit-bindgen = "0.59.0"
wit-parser = { version = "=0.253.0", default-features = false, features = ["std"] }
wasm-encoder = "=0.245.1"

[package.metadata.component]
package = "nlaocs:skript-parser-addon"
