package nlaocs:skript-parser-addon@0.29.0;

world parser-addon {
    import catalog-data;
    import state-store;
    import dynamic-syntax-registry;

    export addon;
    export hooks;
    export text-macro;
    export tree-macro;
    export ast-macro;
}
