[package]
name = "skript-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
fancy-regex = "0.19.0"
thiserror = "2.0.17"
syntax-pattern-parser = { path = "../syntax-pattern-parser" }
syntaxes = { path = "../syntaxes" }

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
proptest = "1.11.0"
