[package]
name = "invalid-syntax-searcher"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "invalid-syntax-searcher"
path = "src/main.rs"

[dependencies]
skripthub = { path = "../../skripthub" }
syntax-pattern-parser = { path = "../../syntax-pattern-parser" }
syntaxes = { path = "../../syntaxes" }

